### ISSUE TITLE
Ship is rolling with left throttle stick max(left) and min(right)

### ISSUE THREAD

**Issue by FinkeStinger** [aboutflash/StarCitizen-WarthogScript#2]
is it normal for the ship to roll when i set the left throttle stick to min or max ?... i thought this stick is just the thruster output ?
pls help ... i cant stand this xD

**Comment by LlamaSauce** [comment]
@FinkeStinger after you load the settings in game check your advanced keybinds. You might have to rebind your throttle and joystick axis.

**Comment by FinkeStinger** [comment]
Thank you ! fixed :D

**Comment by FinkeStinger** [comment]
New Issue showed up ...
when loading the profile ... the console takes quite some time to combine the devices ...
on completion its showing "Thrustmaster combined" + "Throttle - HOTAS Warthog" + "Joystick - HOTAS Warthog" ... istnt it supposed to show just the combined controller ? 
no throttle control ingame when all of these game controllers are listed ... 
any workaround for that ?
thanks in advance

[https://ibb.co/6Jv6x99](url)

[https://ibb.co/LJt0z6B](url)

**Comment by FinkeStinger** [comment]
[https://ibb.co/6Jv6x99](url)

[https://ibb.co/LJt0z6B](url)
